import type { Metadata } from "next";
import Navbar from "@/components/shared/Navbar";
import NextAuthProvider from "@/context/NextAuthProvider";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>

            <NextAuthProvider>
            <Navbar />
            {/* <Toaster position="top-center" reverseOrder={false} /> */}
            <main className="min-h-screen">
                {children}
            </main>

            </NextAuthProvider>


        </div>
    );
}
